#!/bin/bash

cd "$(dirname "$0")"

cmake ../.. && \
make -j12 -C ../.. && \
../../messageGenerator --cpp stressTest.xml --outputFolder . && \
mv -v *.cxx src && \
mv -v *.hxx include && \
cmake . && \
make -j12 && \
./stressTest
