#!/bin/bash

cd "$(dirname "$0")"

if test "../config/Definitions.xsd" -nt "../include/Definitions.hxx" -o \
        "../config/Definitions.xsd" -nt "../src/Definitions.cxx"     -o \
        "$(basename "$0")"          -nt "../include/Definitions.hxx" -o \
        "$(basename "$0")"          -nt "../src/Definitions.cxx"; then
    xsdcxx cxx-tree --std c++11 \
                    --output-dir ../include \
                    --type-naming java \
                    --function-naming java \
                    --generate-ostream \
                    ../config/Definitions.xsd

    mv ../include/Definitions.cxx ../src
fi
